### ISSUE TITLE
Semplici chiarimenti

### ISSUE THREAD

**Issue by replydev** [PsykeDady/Archlinux_installazione#2]
Ciao, volevo innanzitutto farti i complimenti per la completezza e la semplicità della guida.
Solo due chiarimenti:
 - Se volessi contribuire, come modifico il **pdf** e il file **fodt**?
 - Non ritieni che sia più efficace passare allo stile **markdown**? Questo renderebbe la guida più facilmente modificabile e al contempo maggiormente leggibile.

**Comment by mirkobrombin** [comment]
Avevamo già in mente di passare tutto a markdown in modo da renderlo agibile a tutti, il lavoro è però tanto.

Per contribuire puoi scaricare il file fodt, da li esporti poi il pdf.

**Comment by replydev** [comment]
Grazie mille.

**Comment by PsykeDady** [comment]
> Grazie mille.

Ho ricopiato tutto in Markdown :) potete contribuire anche da li ora. 
unica cortesia: rispettate il template alla fine del markdown per i vari stili ( note,  avvertimenti e suggerimenti)
