### ISSUE TITLE
Add systemd-boot

### ISSUE THREAD

**Issue by francescomasala** [PsykeDady/Archlinux_installazione#5]
Add systemd-boot as an alternative to grub

Sorry psyke <3

**Comment by PsykeDady** [comment]
because i don't use systemd-boot, i can add it but i cannot test it. 

Can you write a mini-guide or test a guide if i can write it ?

**Comment by francescomasala** [comment]
Yep, no problem

**Comment by PsykeDady** [comment]
closed for inactivity
